# Generated by Django 2.2.7 on 2019-12-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecat',
            name='isChild',
            field=models.BooleanField(default=False, verbose_name='Детская услуга'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='pages.Service', verbose_name='Предоставляет услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(null=True, to='pages.ServiceCat', verbose_name='Категория услуг'),
        ),
    ]
