# Generated by Django 2.2.7 on 2019-11-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191128_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ico',
            field=models.IntegerField(null=True, verbose_name='Иконко'),
        ),
    ]
