# Generated by Django 2.2.7 on 2019-11-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_service_ico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинко'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ico',
            field=models.ImageField(null=True, upload_to='', verbose_name='Иконко'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинко'),
        ),
    ]
