# Generated by Django 2.2.7 on 2019-12-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191216_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name': 'Запись к врачу', 'verbose_name_plural': 'Записи к врачам'},
        ),
        migrations.AddField(
            model_name='banner',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Service', verbose_name='Ссылается на услугу'),
        ),
    ]
