# Generated by Django 2.2.7 on 2019-11-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191128_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='serv',
        ),
    ]
