# Generated by Django 2.2.7 on 2019-11-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_apply_serv'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинко'),
        ),
    ]
