# Generated by Django 2.2.7 on 2019-12-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='День')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Месяц')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Услуга')),
                ('ico', models.ImageField(null=True, upload_to='', verbose_name='Иконко')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинко')),
                ('tab1', models.CharField(max_length=255, null=True, verbose_name='TAB1 название')),
                ('tab1text', models.CharField(max_length=255, null=True, verbose_name='TAB1 текст')),
                ('tab2', models.CharField(max_length=255, null=True, verbose_name='TAB2 название')),
                ('tab2text', models.CharField(max_length=255, null=True, verbose_name='TAB2 текст')),
                ('tab3', models.CharField(max_length=255, null=True, verbose_name='TAB3 название')),
                ('tab3text', models.CharField(max_length=255, null=True, verbose_name='TAB3 текст')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Время')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='ico',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tab1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tab1text',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tab2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tab2text',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tab3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tab3text',
        ),
        migrations.AddField(
            model_name='apply',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Service'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='info',
            field=models.CharField(max_length=255, null=True, verbose_name='Инфо'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='pages.Service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Doctor'),
        ),
        migrations.AddField(
            model_name='apply',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Day'),
        ),
        migrations.AddField(
            model_name='apply',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Month'),
        ),
        migrations.AddField(
            model_name='apply',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Time'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ServiceCat'),
        ),
    ]
