# Generated by Django 2.2.7 on 2019-12-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191201_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(null=True, to='pages.ServiceCat'),
        ),
    ]
