# Generated by Django 2.2.7 on 2020-01-07 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200107_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.SubService'),
        ),
    ]
