# Generated by Django 2.2.7 on 2020-01-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200107_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cabinet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка 100x100'),
        ),
        migrations.AlterField(
            model_name='servicecat',
            name='ico',
            field=models.ImageField(null=True, upload_to='', verbose_name='Иконка для меню 100x100'),
        ),
    ]
