# Generated by Django 2.2.7 on 2019-12-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191201_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуга'),
        ),
        migrations.AlterField(
            model_name='servicecat',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория услуг'),
        ),
    ]
