# Generated by Django 2.2.7 on 2020-01-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applyTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Точное время заявки'),
        ),
        migrations.AddField(
            model_name='apply',
            name='isApprove',
            field=models.BooleanField(default=False, verbose_name='Подтверждена?'),
        ),
    ]
