# Generated by Django 2.2.7 on 2020-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200203_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='pages.ServiceCat', verbose_name='Предоставляет услуги'),
        ),
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
