# Generated by Django 2.2.7 on 2020-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200210_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='info',
            field=models.TextField(null=True, verbose_name='Инфо'),
        ),
    ]
