# Generated by Django 2.2.7 on 2020-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200304_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
