# Generated by Django 2.2.7 on 2020-03-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_apply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='servicee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Service'),
        ),
    ]
