# Generated by Django 2.2.7 on 2020-03-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_apply_servicee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.SubService'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='servicee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Service'),
        ),
    ]
